export const BENTO_UI_WIDGET_TYPES: { [key: string]: string } = {
  ROUTINE: "ROUTINE",
  CALENDAR: "CALENDAR",
  IDENTITY: "IDENTITY",
  PERSONALIZATION: "PERSONALIZATION",
  VISION_BOARD: "VISION_BOARD",
};
